### ISSUE TITLE
FIDO2 Server  MDS tests issue - https://mds3.fido.tools/getTestMetadata returns 404

### ISSUE THREAD

**Issue by vs-nnl** [fido-alliance/conformance-test-tools-resources#698] opened 2023-02-03 20:15 UTC
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [X ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [X ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.9

## What is the OS and the version are you running?

For desktop tools
- [X ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

FIDO Conformance Tools v1.7.9 || FIDO2 Server - MDS3.
Metadata Service Tests are failing. The conformance tool tries to access the URL https://mds3.fido.tools/getTestMetadata, but it returns HTTP status code 404.

**Comment by herrjemand** [comment] 2023-02-03 22:31
@vs-nnl try now?

**Comment by vs-nnl** [comment] 2023-02-03 22:47
@herrjemand Thanks for the quick response. Unfortunately, it's still not working.

**Comment by herrjemand** [comment] 2023-02-04 02:03
@vs-nnl Are the tools not working for you or are you trying to access API directly? Because getTestMetadata is POST not get

**Comment by herrjemand** [comment] 2023-02-04 02:18
@vs-nnl try regenerating endpoints

**Comment by vs-nnl** [comment] 2023-02-04 06:51
@herrjemand Still no luck. The errors occur in the tool. Please see attached screenshot.
<img width="1670" alt="Screen Shot 2023-02-03 at 10 49 35 PM" src="https://user-images.githubusercontent.com/13699587/216753521-0464db8b-5d7b-4854-ae32-46d35013d1fe.png">

**Comment by ThaminduDilshan** [comment] 2023-03-02 05:09
This issue is still reproducible. `v1.7.9`
@herrjemand Can we get a fix for this issue? To me this looks like a issue with conformance tool.

<img width="1527" alt="Screenshot 2023-03-02 at 10 37 14 AM" src="https://user-images.githubusercontent.com/35653110/222336390-2bbd4f0f-91ad-4a01-a12e-911fad8c7582.png">

**Comment by MisatoKatsuragi** [comment] 2023-03-02 13:32
Hello,

We have the same issue with the conformance tool 1.7.6 version.
It returns HTTP status code 404 because the tool is doing a GET request instead of POST

**Comment by herrjemand** [comment] 2023-03-03 10:09
Ok, I think I nailed down the issues. New build up tonight

**Comment by aicfr** [comment] 2023-03-06 09:24
Hello @herrjemand,

URL https://mds3.fido.tools/getTestMetadata always returns HTTP status code 404 and I can't find new versions of tool (v1.8.0 ?)

Thanks 😃

**Comment by aseigler** [comment] 2023-03-07 20:01
> URL https://mds3.fido.tools/getTestMetadata always returns HTTP status code 404

This part is still broken.

**Comment by herrjemand** [comment] 2023-03-08 10:32
@aseigler try 1.7.10

**Comment by aseigler** [comment] 2023-03-08 13:11
> @aseigler try 1.7.10

![image](https://user-images.githubusercontent.com/6605560/223721516-db3ad507-7bf3-4cfc-899d-d0b297197ce1.png)

Additionally, all of the `GetAssertion Response` tests are completely broken in this build.

**Comment by herrjemand** [comment] 2023-03-08 13:20
That does not look like it's updated properly... let me check...

Yuriy Ackermann
FIDO, Identity, Standards
skype: ackermann.yuriy
github: @herrjemand <https://github.com/herrjemand>
twitter: @herrjemand <https://twitter.com/herrjemand>
medium: @herrjemand ***@***.***>

**Comment by herrjemand** [comment] 2023-03-13 12:33
<img width="423" alt="Screenshot 2023-03-13 at 15 28 27" src="https://user-images.githubusercontent.com/1636116/224702759-5d5281a0-47c3-4d54-83dc-9b80b826aae3.png">

I've setup test env, and can confirm that its works in [1.7.10](https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.10/)

Try going to https://mds3.fido.tools/ and regenerating your MDS3 endpoints.

**Closed by herrjemand** 2023-03-13 12:33 UTC
